name: Prisma Migrate Deploy
on:
  workflow_call:
    inputs:
      node-env:
        required: true
        type: string
    secrets:
      DEV_DATABASE_URL:
        required: true
      PROD_DATABASE_URL:
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Set database endpoint
        id: set-secrets
        run: |
          if [ "${{ inputs.node-env }}" = "prod" ]; then
             echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> $GITHUB_OUTPUT
           else
             echo "DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}" >> $GITHUB_OUTPUT
          fi
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ steps.set-secrets.outputs.DATABASE_URL }}